-- Tabela para Atas de Reunião
CREATE TABLE meeting_minutes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date DATE NOT NULL,
  file_url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Tabela para Links de Reunião
CREATE TABLE meeting_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  date DATE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Habilitar RLS (Row Level Security)
ALTER TABLE meeting_minutes ENABLE ROW LEVEL SECURITY;
ALTER TABLE meeting_links ENABLE ROW LEVEL SECURITY;

-- Políticas de acesso para Atas (Leitura e Escrita liberadas para o app)
CREATE POLICY "Permitir acesso total às atas" ON meeting_minutes FOR ALL USING (true);

-- Políticas de acesso para Links (Leitura e Escrita liberadas para o app)
CREATE POLICY "Permitir acesso total aos links" ON meeting_links FOR ALL USING (true);

-- Criar o bucket de storage para os arquivos das atas
INSERT INTO storage.buckets (id, name, public) VALUES ('meeting-files', 'meeting-files', true);

-- Políticas de Storage para o bucket 'meeting-files'
CREATE POLICY "Permitir leitura pública de arquivos de reunião" ON storage.objects FOR SELECT USING (bucket_id = 'meeting-files');
CREATE POLICY "Permitir upload de arquivos de reunião" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'meeting-files');
CREATE POLICY "Permitir deleção de arquivos de reunião" ON storage.objects FOR DELETE USING (bucket_id = 'meeting-files');
