
-- ==========================================
-- ESQUEMA DE BANCO DE DADOS - ATLAS 2026
-- ==========================================

-- 1. Tabela de Cargos e Permissões
CREATE TABLE IF NOT EXISTS public.user_roles (
    user_id uuid REFERENCES auth.users NOT NULL,
    role text NOT NULL,
    created_at timestamptz DEFAULT now()
    -- A Primary Key será definida/atualizada no bloco abaixo
);

-- MIGRACAO PARA SUPORTAR MULTIPLOS CARGOS
-- Transforma a PK em composta (user_id, role) para permitir vários cargos
DO $$ 
BEGIN
    -- Se existir uma PK antiga simples (apenas user_id), removemos
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_roles_pkey') THEN
        ALTER TABLE public.user_roles DROP CONSTRAINT user_roles_pkey;
    END IF;
    
    -- Adiciona a nova PK composta se não existir
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_roles_pkey_composite') THEN
         -- Tenta adicionar com nome específico para evitar conflitos futuros
         ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_pkey_composite PRIMARY KEY (user_id, role);
    END IF;
EXCEPTION
    WHEN others THEN 
        -- Fallback seguro: se der erro, tenta adicionar a PK padrão composta
        BEGIN
            ALTER TABLE public.user_roles ADD PRIMARY KEY (user_id, role);
        EXCEPTION WHEN others THEN NULL; END;
END $$;

-- ATUALIZAÇÃO SEGURA DE CARGOS (Check Constraints):
DO $$ 
BEGIN
    ALTER TABLE public.user_roles DROP CONSTRAINT IF EXISTS user_roles_role_check;
    ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_role_check 
    CHECK (role IN ('ADM', 'FINANCEIRO', 'MARKETING', 'EVENTOS', 'JURIDICO', 'MEMBER'));
EXCEPTION
    WHEN others THEN NULL;
END $$;

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Ler o proprio cargo" ON public.user_roles;
DROP POLICY IF EXISTS "Inserir cargo inicial" ON public.user_roles;

CREATE POLICY "Ler o proprio cargo" ON public.user_roles FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Inserir cargo inicial" ON public.user_roles FOR INSERT WITH CHECK (auth.uid() = user_id);

-- ==========================================
-- TABELAS DE DADOS
-- ==========================================

CREATE TABLE IF NOT EXISTS public.tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    status text NOT NULL,
    category text,
    assigned_to text,
    deadline timestamptz,
    urgency text,
    created_at timestamptz DEFAULT now(),
    completed_at timestamptz
);

CREATE TABLE IF NOT EXISTS public.transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric NOT NULL,
    type text NOT NULL,
    category text,
    date date,
    description text,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    event_date timestamptz,
    location text,
    capacity int,
    category text,
    description text,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.marketing_posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caption text,
    platform text,
    scheduled_date date,
    image_url text,
    status text DEFAULT 'scheduled',
    likes_count int DEFAULT 0,
    comments_count int DEFAULT 0,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    file_url text,
    related_party text,
    status text DEFAULT 'pending',
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.committee_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    role text,
    phone text,
    photo_url text,
    cpf text,
    address text,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.polls (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text,
    deadline timestamptz,
    options text[],
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.votes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id bigint REFERENCES public.polls(id) ON DELETE CASCADE,
    option_selected text NOT NULL,
    user_id uuid DEFAULT auth.uid(),
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.game_scores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_name text NOT NULL,
    score int NOT NULL,
    game_type text NOT NULL,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.app_feedback (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email text,
    type text,
    message text,
    view_context text,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.meeting_minutes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    date date,
    file_url text,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.meeting_links (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    url text NOT NULL,
    date date,
    created_at timestamptz DEFAULT now()
);

-- Add new columns to transactions if they don't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'transactions' AND column_name = 'event_context') THEN
        ALTER TABLE public.transactions ADD COLUMN event_context text;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'transactions' AND column_name = 'file_url') THEN
        ALTER TABLE public.transactions ADD COLUMN file_url text;
    END IF;
END $$;

-- ==========================================
-- POLÍTICAS DE SEGURANÇA (RLS)
-- ==========================================

DO $$ 
BEGIN
    -- TASKS
    ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Tasks" ON public.tasks;
    CREATE POLICY "Acesso total Tasks" ON public.tasks FOR ALL TO authenticated USING (true);

    -- TRANSACTIONS
    ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Transactions" ON public.transactions;
    CREATE POLICY "Acesso total Transactions" ON public.transactions FOR ALL TO authenticated USING (true);

    -- EVENTS
    ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Events" ON public.events;
    CREATE POLICY "Acesso total Events" ON public.events FOR ALL TO authenticated USING (true);

    -- MARKETING
    ALTER TABLE public.marketing_posts ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Marketing" ON public.marketing_posts;
    CREATE POLICY "Acesso total Marketing" ON public.marketing_posts FOR ALL TO authenticated USING (true);

    -- DOCUMENTS
    ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Documents" ON public.documents;
    CREATE POLICY "Acesso total Documents" ON public.documents FOR ALL TO authenticated USING (true);

    -- MEMBERS (Aqui garantimos que TODOS podem criar/editar)
    ALTER TABLE public.committee_members ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Members" ON public.committee_members;
    CREATE POLICY "Acesso total Members" ON public.committee_members FOR ALL TO authenticated USING (true);

    -- POLLS
    ALTER TABLE public.polls ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Polls" ON public.polls;
    CREATE POLICY "Acesso total Polls" ON public.polls FOR ALL TO authenticated USING (true);

    -- VOTES
    ALTER TABLE public.votes ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Votes" ON public.votes;
    CREATE POLICY "Acesso total Votes" ON public.votes FOR ALL TO authenticated USING (true);

    -- SCORES
    ALTER TABLE public.game_scores ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Scores" ON public.game_scores;
    CREATE POLICY "Acesso total Scores" ON public.game_scores FOR ALL TO authenticated USING (true);

    -- FEEDBACK
    ALTER TABLE public.app_feedback ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Feedback" ON public.app_feedback;
    CREATE POLICY "Acesso total Feedback" ON public.app_feedback FOR ALL TO authenticated USING (true);

    -- MEETING MINUTES
    ALTER TABLE public.meeting_minutes ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Minutes" ON public.meeting_minutes;
    CREATE POLICY "Acesso total Minutes" ON public.meeting_minutes FOR ALL TO authenticated USING (true);

    -- MEETING LINKS
    ALTER TABLE public.meeting_links ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Links" ON public.meeting_links;
    CREATE POLICY "Acesso total Links" ON public.meeting_links FOR ALL TO authenticated USING (true);

    -- EVENT COSTS (ETL Integration)
    CREATE TABLE IF NOT EXISTS public.event_costs (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_name text NOT NULL,
        category text NOT NULL,
        item_name text NOT NULL,
        quantity numeric DEFAULT 1,
        unit_price numeric,
        total_price numeric NOT NULL,
        receipt_url text,
        status text DEFAULT 'planned',
        created_at timestamptz DEFAULT now(),
        updated_at timestamptz DEFAULT now(),
        UNIQUE(event_name, category, item_name)
    );
    ALTER TABLE public.event_costs ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Event Costs" ON public.event_costs;
    CREATE POLICY "Acesso total Event Costs" ON public.event_costs FOR ALL TO authenticated USING (true);
END $$;

-- ==========================================
-- STORAGE (Arquivos)
-- ==========================================
INSERT INTO storage.buckets (id, name, public) 
VALUES 
  ('member-avatars', 'member-avatars', true),
  ('legal-docs', 'legal-docs', true),
  ('marketing-images', 'marketing-images', true),
  ('meeting-files', 'meeting-files', true),
  ('finance-receipts', 'finance-receipts', true)
ON CONFLICT (id) DO NOTHING;

DO $$
BEGIN
    -- Avatars
    DROP POLICY IF EXISTS "Avatars Publicos" ON storage.objects;
    CREATE POLICY "Avatars Publicos" ON storage.objects FOR SELECT USING ( bucket_id = 'member-avatars' );
    DROP POLICY IF EXISTS "Avatars Upload" ON storage.objects;
    CREATE POLICY "Avatars Upload" ON storage.objects FOR INSERT TO authenticated WITH CHECK ( bucket_id = 'member-avatars' );

    -- Docs
    DROP POLICY IF EXISTS "Docs Publicos" ON storage.objects;
    CREATE POLICY "Docs Publicos" ON storage.objects FOR SELECT USING ( bucket_id = 'legal-docs' );
    DROP POLICY IF EXISTS "Docs Upload" ON storage.objects;
    CREATE POLICY "Docs Upload" ON storage.objects FOR INSERT TO authenticated WITH CHECK ( bucket_id = 'legal-docs' );

    -- Marketing
    DROP POLICY IF EXISTS "Marketing Publicos" ON storage.objects;
    CREATE POLICY "Marketing Publicos" ON storage.objects FOR SELECT USING ( bucket_id = 'marketing-images' );
    DROP POLICY IF EXISTS "Marketing Upload" ON storage.objects;
    CREATE POLICY "Marketing Upload" ON storage.objects FOR INSERT TO authenticated WITH CHECK ( bucket_id = 'marketing-images' );

    -- Meeting Files
    DROP POLICY IF EXISTS "Meeting Publicos" ON storage.objects;
    CREATE POLICY "Meeting Publicos" ON storage.objects FOR SELECT USING ( bucket_id = 'meeting-files' );
    DROP POLICY IF EXISTS "Meeting Upload" ON storage.objects;
    CREATE POLICY "Meeting Upload" ON storage.objects FOR INSERT TO authenticated WITH CHECK ( bucket_id = 'meeting-files' );

    -- Finance Receipts
    DROP POLICY IF EXISTS "Finance Publicos" ON storage.objects;
    CREATE POLICY "Finance Publicos" ON storage.objects FOR SELECT USING ( bucket_id = 'finance-receipts' );
    DROP POLICY IF EXISTS "Finance Upload" ON storage.objects;
    CREATE POLICY "Finance Upload" ON storage.objects FOR INSERT TO authenticated WITH CHECK ( bucket_id = 'finance-receipts' );
END $$;
