
-- ==========================================
-- ESQUEMA DE BANCO DE DADOS - ATLAS 2026
-- ==========================================

-- 1. Tabela de Cargos e Permissões
-- Cria a tabela se não existir
CREATE TABLE IF NOT EXISTS public.user_roles (
    user_id uuid REFERENCES auth.users NOT NULL PRIMARY KEY,
    role text NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- ATUALIZAÇÃO SEGURA DE CARGOS (Migração para Português):
-- Este bloco remove a regra antiga (se existir) e aplica a nova com os cargos:
-- ADM, FINANCEIRO, MARKETING, EVENTOS, JURIDICO, MEMBER
DO $$ 
BEGIN
    -- Tenta remover a restrição antiga se ela existir
    ALTER TABLE public.user_roles DROP CONSTRAINT IF EXISTS user_roles_role_check;
    
    -- Adiciona a nova restrição com os nomes em português
    ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_role_check 
    CHECK (role IN ('ADM', 'FINANCEIRO', 'MARKETING', 'EVENTOS', 'JURIDICO', 'MEMBER'));
EXCEPTION
    WHEN others THEN NULL; -- Ignora erros se a constraint não existir
END $$;

-- Habilita segurança (RLS)
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Reseta políticas para evitar duplicação
DROP POLICY IF EXISTS "Ler o proprio cargo" ON public.user_roles;
DROP POLICY IF EXISTS "Inserir cargo inicial" ON public.user_roles;
DROP POLICY IF EXISTS "Admins podem atualizar cargos" ON public.user_roles;

-- Permite que o usuário veja seu próprio cargo
CREATE POLICY "Ler o proprio cargo" ON public.user_roles 
FOR SELECT USING (auth.uid() = user_id);

-- Permite que o sistema registre o cargo no primeiro login
CREATE POLICY "Inserir cargo inicial" ON public.user_roles 
FOR INSERT WITH CHECK (auth.uid() = user_id);

-- ==========================================
-- TABELAS DE DADOS
-- ==========================================

-- 2. Tabela de Tarefas (Kanban)
CREATE TABLE IF NOT EXISTS public.tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    status text NOT NULL,
    category text,
    assigned_to text,
    deadline timestamptz,
    urgency text,
    created_at timestamptz DEFAULT now(),
    completed_at timestamptz
);

-- 3. Tabela de Transações (Financeiro)
CREATE TABLE IF NOT EXISTS public.transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric NOT NULL,
    type text NOT NULL,
    category text,
    date date,
    description text,
    created_at timestamptz DEFAULT now()
);

-- 4. Tabela de Eventos
CREATE TABLE IF NOT EXISTS public.events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    event_date timestamptz,
    location text,
    capacity int,
    category text,
    description text,
    created_at timestamptz DEFAULT now()
);

-- 5. Tabela de Marketing
CREATE TABLE IF NOT EXISTS public.marketing_posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caption text,
    platform text,
    scheduled_date date,
    image_url text,
    status text DEFAULT 'scheduled',
    likes_count int DEFAULT 0,
    comments_count int DEFAULT 0,
    created_at timestamptz DEFAULT now()
);

-- 6. Tabela de Documentos (Jurídico)
CREATE TABLE IF NOT EXISTS public.documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    file_url text,
    related_party text,
    status text DEFAULT 'pending',
    created_at timestamptz DEFAULT now()
);

-- 7. Tabela de Membros
CREATE TABLE IF NOT EXISTS public.committee_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    role text,
    phone text,
    photo_url text,
    cpf text,
    address text,
    created_at timestamptz DEFAULT now()
);

-- 8. Tabelas de Votação
CREATE TABLE IF NOT EXISTS public.polls (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text,
    deadline timestamptz,
    options text[],
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.votes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id bigint REFERENCES public.polls(id) ON DELETE CASCADE,
    option_selected text NOT NULL,
    user_id uuid DEFAULT auth.uid(),
    created_at timestamptz DEFAULT now()
);

-- 9. Tabela de Games (Score)
CREATE TABLE IF NOT EXISTS public.game_scores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_name text NOT NULL,
    score int NOT NULL,
    game_type text NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- 10. Feedback
CREATE TABLE IF NOT EXISTS public.app_feedback (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email text,
    type text,
    message text,
    view_context text,
    created_at timestamptz DEFAULT now()
);

-- ==========================================
-- POLÍTICAS DE SEGURANÇA (RLS)
-- ==========================================
-- Configura permissão total para usuários autenticados nas tabelas de dados.
-- O controle fino (quem pode editar o que) é feito no Frontend (App.tsx e KanbanBoard.tsx).

DO $$ 
BEGIN
    -- Loop para aplicar políticas em todas as tabelas
    -- Tasks
    ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Tasks" ON public.tasks;
    CREATE POLICY "Acesso total Tasks" ON public.tasks FOR ALL TO authenticated USING (true);

    -- Transactions
    ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Transactions" ON public.transactions;
    CREATE POLICY "Acesso total Transactions" ON public.transactions FOR ALL TO authenticated USING (true);

    -- Events
    ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Events" ON public.events;
    CREATE POLICY "Acesso total Events" ON public.events FOR ALL TO authenticated USING (true);

    -- Marketing
    ALTER TABLE public.marketing_posts ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Marketing" ON public.marketing_posts;
    CREATE POLICY "Acesso total Marketing" ON public.marketing_posts FOR ALL TO authenticated USING (true);

    -- Documents
    ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Documents" ON public.documents;
    CREATE POLICY "Acesso total Documents" ON public.documents FOR ALL TO authenticated USING (true);

    -- Members
    ALTER TABLE public.committee_members ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Members" ON public.committee_members;
    CREATE POLICY "Acesso total Members" ON public.committee_members FOR ALL TO authenticated USING (true);

    -- Polls
    ALTER TABLE public.polls ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Polls" ON public.polls;
    CREATE POLICY "Acesso total Polls" ON public.polls FOR ALL TO authenticated USING (true);

    -- Votes
    ALTER TABLE public.votes ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Votes" ON public.votes;
    CREATE POLICY "Acesso total Votes" ON public.votes FOR ALL TO authenticated USING (true);

    -- Game Scores
    ALTER TABLE public.game_scores ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Scores" ON public.game_scores;
    CREATE POLICY "Acesso total Scores" ON public.game_scores FOR ALL TO authenticated USING (true);

    -- Feedback
    ALTER TABLE public.app_feedback ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Acesso total Feedback" ON public.app_feedback;
    CREATE POLICY "Acesso total Feedback" ON public.app_feedback FOR ALL TO authenticated USING (true);
END $$;

-- ==========================================
-- STORAGE (Arquivos)
-- ==========================================
-- Cria os buckets se não existirem
INSERT INTO storage.buckets (id, name, public) 
VALUES 
  ('member-avatars', 'member-avatars', true),
  ('legal-docs', 'legal-docs', true)
ON CONFLICT (id) DO NOTHING;

-- Configura políticas de upload e download
DO $$
BEGIN
    -- Avatars
    DROP POLICY IF EXISTS "Avatars Publicos" ON storage.objects;
    CREATE POLICY "Avatars Publicos" ON storage.objects FOR SELECT USING ( bucket_id = 'member-avatars' );
    
    DROP POLICY IF EXISTS "Avatars Upload" ON storage.objects;
    CREATE POLICY "Avatars Upload" ON storage.objects FOR INSERT TO authenticated WITH CHECK ( bucket_id = 'member-avatars' );

    -- Docs
    DROP POLICY IF EXISTS "Docs Publicos" ON storage.objects;
    CREATE POLICY "Docs Publicos" ON storage.objects FOR SELECT USING ( bucket_id = 'legal-docs' );

    DROP POLICY IF EXISTS "Docs Upload" ON storage.objects;
    CREATE POLICY "Docs Upload" ON storage.objects FOR INSERT TO authenticated WITH CHECK ( bucket_id = 'legal-docs' );
END $$;
